In [1]:
#import all the required library
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import statistics
from scipy.stats import sem

In [2]:
df_bert = pd.read_csv('D:/IIITD/Mansi_Thesis_Research/Foodprint/Github-SustainableFoodDB/Data/Mapped/bert_nli_recipedb_sueat_mapping.csv')

In [3]:
input_file = df_bert[(df_bert['Similarity'] > 0.81)]
input_file.drop(columns='Unnamed: 0')

                      RecipeDB Ingredient   Sueatable Ingredient  Similarity
1                                   onion                  ONION    1.000001
2                                  butter                 BUTTER    1.000000
3                            garlic clove                 GARLIC    0.930919
4                                   water                  WATER    1.000000
5                               olive oil              OLIVE OIL    1.000000
...                                   ...                    ...         ...
20274                 dutch cocoa hershey     HAZELNUT CHOCOLATE    0.823729
20275              milk chocolate hershey         MILK CHOCOLATE    0.947778
20276  chocolate flavor crisp rice cereal  CHOCOLATE CREAM COOKY    0.818652
20277          chocolate ripple ice cream  CHOCOLATE CREAM COOKY    0.925916
20278               caramel topping syrup        CRANBERRY JUICE    0.852054

[7753 rows x 3 columns]

In [4]:
input_file.to_csv('D:/IIITD/Mansi_Thesis_Research/Foodprint/Github-SustainableFoodDB/Data/Mapped/Recipedb_sueat_cutoff_mapped_ing.csv', index=False)

In [5]:
#read csv file for Food Items of sueatable
input_file_fooditem = pd.read_csv('D:/IIITD/Mansi_Thesis_Research/Foodprint/Github-SustainableFoodDB/Data/Food_Items_CF_clean_1.csv', encoding='latin1')

In [6]:
input_file_fooditem

,FOOD COMMODITY GROUP,FOOD COMMODITY TYPOLOGY,FOOD COMMODITY TYPOLOGY updated,FOOD COMMODITY sub-TYPOLOGY,FOOD COMMODITY ITEM,FOOD COMMODITY ITEM updated,SYNONYMS,URL,n,mean,...,Q1,Q3,CV,skewness,kurtosis,Shapiro Wilk test P,FLAG 1 (SIZE),FLAG 2 (outlier),FLAG 3 (adherence to the normal distribution),Suggested CF value to represent food commodity
0,AGRICULTURAL PROCESSED,BEER,BEER,-,BEER IN CAN,BEER IN CAN,NaN,NaN,5,0.69,...,0.58,0.77,0.2,0.878,2.62,0.329,Y,G,G,ITEM
1,AGRICULTURAL PROCESSED,BEER,BEER,-,BEER IN GLASS,BEER IN GLASS,NaN,NaN,9,1.03,...,0.67,1.17,0.5,1.117,3.412,0.275,G,G,G,ITEM
2,AGRICULTURAL PROCESSED,BEER,BEER,-,BEER MODULAR CAN,BEER MODULAR CAN,NaN,NaN,5,0.54,...,0.52,0.58,0.06,0.273,1.354,0.394,Y,G,G,ITEM
3,AGRICULTURAL PROCESSED,BISCUITS,BISCUIT,-,CHOCOLATE OR CREAM FILLED COOKIES,CHOCOLATE CREAM COOKY,NaN,NaN,9,1.69,...,1.45,1.69,0.23,1.126,2.554,0.005,G,G,R,ITEM
4,AGRICULTURAL PROCESSED,BISCUITS,BISCUIT,-,SIMPLE COOKIES,COOKY,NaN,NaN,12,1.50,...,1.25,1.60,0.23,1.183,3.6,0.078,G,G,G,ITEM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,FISHING,SHELLFISH,SHELLFISH,CRUSTACEAN* (SUB-TYP) (PRAWN/SHRIMP),PRAWN,PRAWN,NaN,NaN,18,11.95,...,5.24,16.78,0.87,1.282,3.37,0.001,G,G,R,ITEM
298,FISHING,SHELLFISH,SHELLFISH,CRUSTACEAN* (SUB-TYP) (PRAWN/SHRIMP),SHRIMP,SHRIMP,NaN,NaN,18,11.95,...,5.24,16.78,0.87,1.282,3.37,0.001,G,G,R,ITEM
299,FISHING,SHELLFISH FROZEN,SHELLFISH FROZEN,-,OCTOPUS (F),OCTOPUS FROZEN,NaN,NaN,1,7.88,...,7.88,7.88,-,-,-,n.a.,R,G,R,TYPOLOGY
300,FISHING,SHELLFISH FROZEN,SHELLFISH FROZEN,-,SHRIMP (F),SHRIMP FROZEN,NaN,NaN,4,17.73,...,6.85,25.95,0.68,0.348,1.461,0.381,Y,G,G,ITEM
301,FISHING,SHELLFISH FROZEN,SHELLFISH FROZEN,-,PRAWN (F),PRAWN FROZEN,NaN,NaN,4,17.73,...,6.85,25.95,0.68,0.348,1.461,0.381,Y,G,G,ITEM

In [7]:
input_file_fooditem = input_file_fooditem[['FOOD COMMODITY ITEM updated','mean']]
input_file_fooditem

    FOOD COMMODITY ITEM updated   mean
0                   BEER IN CAN   0.69
1                 BEER IN GLASS   1.03
2              BEER MODULAR CAN   0.54
3         CHOCOLATE CREAM COOKY   1.69
4                         COOKY   1.50
..                          ...    ...
297                       PRAWN  11.95
298                      SHRIMP  11.95
299              OCTOPUS FROZEN   7.88
300               SHRIMP FROZEN  17.73
301                PRAWN FROZEN  17.73

[302 rows x 2 columns]

In [8]:
input_file_fooditem.to_csv('D:/IIITD/Mansi_Thesis_Research/Foodprint/Github-SustainableFoodDB/Data/Mapped/Sueatable_ing_CF.csv', index=False)

In [9]:
for i in input_file_fooditem['FOOD COMMODITY ITEM updated']:
    if i in input_file['Sueatable Ingredient'].values:
        cf_value = input_file_fooditem.loc[input_file_fooditem['FOOD COMMODITY ITEM updated'] == i, 'mean'].values[0]
        input_file.loc[input_file['Sueatable Ingredient'] == i, 'CF'] = cf_value
input_file = input_file.drop(columns='Unnamed: 0')

C:\Users\Mansi Goel\AppData\Local\Temp\ipykernel_8128\1547982858.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  input_file.loc[input_file['Sueatable Ingredient'] == i, 'CF'] = cf_value

In [10]:
input_file.to_csv('D:/IIITD/Mansi_Thesis_Research/Foodprint/Github-SustainableFoodDB/Data/Mapped/Recipedb_mapped_ing_CF.csv', index=False)

# Unmapped

In [11]:
merged_df = df_bert.merge(input_file, on='RecipeDB Ingredient', how='left', indicator=True)

# Select rows that are only in df_bert (not in input_file)
rows_only_in_df_bert = merged_df[merged_df['_merge'] == 'left_only']

# Get the list of indices or values from the result
list_of_indices = rows_only_in_df_bert.index.tolist()
unmapped_ing = rows_only_in_df_bert['RecipeDB Ingredient'].tolist()

In [12]:
unmap = pd.DataFrame()
unmap['RecipeDB Ingredient'] = unmapped_ing

In [13]:
unmap.to_csv('D:/IIITD/Mansi_Thesis_Research/Foodprint/Github-SustainableFoodDB/Data/Mapped/Unmapped_RecipeDB_ingredient.csv', index=False)