In [2]:
import pandas as pd

In [3]:
cat = pd.read_csv("D:\IIITD\Mansi_Thesis_Research\Foodprint\Carbon_Footprint_July23\Data\Category\Recipedb_ing_category.csv")
ing = pd.read_csv("D:\IIITD\Mansi_Thesis_Research\Foodprint\Carbon_Footprint_July23\Data\Mapped\Recipedb_mapped_ing_CF_count.csv")

In [4]:
cat

          RecipeDB Ingredient         generic_name Dietrx_Category
0                        salt                 Salt        Additive
1                       onion                Onion       Vegetable
2                      butter               Butter           Dairy
3                       water                Water        Additive
4                garlic clove               Garlic            Herb
...                       ...                  ...             ...
19014         zucchini squash             Zucchini       Vegetable
19015  zucchini summer squash        Summer Squash           Fruit
19016   zucchini tomato sauce         Tomato Sauce       Condiment
19017     zwieback breadcrumb          Bread Crumb          Bakery
19018          zwieback cooky  Amaretti di Saronno            Dish

[19019 rows x 3 columns]

In [5]:
ing

,RecipeDB Ingredient,Sueatable Ingredient,Similarity,CF,Count
0,onion,ONION,1.000001,0.24,69096.0
1,butter,BUTTER,1.000000,9.90,54026.0
2,garlic clove,GARLIC,0.930919,0.67,49786.0
3,water,WATER,1.000000,0.49,49546.0
4,olive oil,OLIVE OIL,1.000000,3.84,44782.0
...,...,...,...,...,...
7748,dutch cocoa hershey,HAZELNUT CHOCOLATE,0.823729,3.43,2.0
7749,milk chocolate hershey,MILK CHOCOLATE,0.947778,3.60,2.0
7750,chocolate flavor crisp rice cereal,CHOCOLATE CREAM COOKY,0.818652,1.69,2.0
7751,chocolate ripple ice cream,CHOCOLATE CREAM COOKY,0.925916,1.69,2.0
7752,caramel topping syrup,CRANBERRY JUICE,0.852054,2.88,2.0

In [6]:
ing_cat = pd.merge(cat,ing,on='RecipeDB Ingredient', how='right')

# If an ingredient is present in 'ing' but category is not present, fill with NaN
ing_cat.loc[ing_cat['Dietrx_Category'].isnull(), 'Dietrx_Category'] = pd.NA

ing_cat = ing_cat.drop(columns={'generic_name'})
ing_cat

,RecipeDB Ingredient,Dietrx_Category,Sueatable Ingredient,Similarity,CF,Count
0,onion,Vegetable,ONION,1.000001,0.24,69096.0
1,butter,Dairy,BUTTER,1.000000,9.90,54026.0
2,garlic clove,Herb,GARLIC,0.930919,0.67,49786.0
3,water,Additive,WATER,1.000000,0.49,49546.0
4,olive oil,Plant Derivative,OLIVE OIL,1.000000,3.84,44782.0
...,...,...,...,...,...,...
7748,dutch cocoa hershey,Plant,HAZELNUT CHOCOLATE,0.823729,3.43,2.0
7749,milk chocolate hershey,Beverage,MILK CHOCOLATE,0.947778,3.60,2.0
7750,chocolate flavor crisp rice cereal,Cereal,CHOCOLATE CREAM COOKY,0.818652,1.69,2.0
7751,chocolate ripple ice cream,Dish,CHOCOLATE CREAM COOKY,0.925916,1.69,2.0
7752,caramel topping syrup,Additive,CRANBERRY JUICE,0.852054,2.88,2.0

In [7]:
sueat = pd.read_csv("D:\IIITD\Mansi_Thesis_Research\Foodprint\Carbon_Footprint_July23\Data\Food_Items_CF_clean_1.csv")
sueat = sueat.rename(columns={'FOOD COMMODITY ITEM updated':'Sueatable Ingredient'})
# sueat['Sueatable Ingredient'] = sueat['Sueatable Ingredient'].apply(lambda x: x.title())

sueat = sueat.iloc[:, :6]
sueat

,FOOD COMMODITY GROUP,FOOD COMMODITY TYPOLOGY,FOOD COMMODITY TYPOLOGY updated,FOOD COMMODITY sub-TYPOLOGY,FOOD COMMODITY ITEM,Sueatable Ingredient
0,AGRICULTURAL PROCESSED,BEER,BEER,-,BEER IN CAN,BEER IN CAN
1,AGRICULTURAL PROCESSED,BEER,BEER,-,BEER IN GLASS,BEER IN GLASS
2,AGRICULTURAL PROCESSED,BEER,BEER,-,BEER MODULAR CAN,BEER MODULAR CAN
3,AGRICULTURAL PROCESSED,BISCUITS,BISCUIT,-,CHOCOLATE OR CREAM FILLED COOKIES,CHOCOLATE CREAM COOKY
4,AGRICULTURAL PROCESSED,BISCUITS,BISCUIT,-,SIMPLE COOKIES,COOKY
...,...,...,...,...,...,...
297,FISHING,SHELLFISH,SHELLFISH,CRUSTACEAN* (SUB-TYP) (PRAWN/SHRIMP),PRAWN,PRAWN
298,FISHING,SHELLFISH,SHELLFISH,CRUSTACEAN* (SUB-TYP) (PRAWN/SHRIMP),SHRIMP,SHRIMP
299,FISHING,SHELLFISH FROZEN,SHELLFISH FROZEN,-,OCTOPUS (F),OCTOPUS FROZEN
300,FISHING,SHELLFISH FROZEN,SHELLFISH FROZEN,-,SHRIMP (F),SHRIMP FROZEN
301,FISHING,SHELLFISH FROZEN,SHELLFISH FROZEN,-,PRAWN (F),PRAWN FROZEN

In [8]:
df1 = pd.merge(ing_cat,sueat, on='Sueatable Ingredient')
df1 = df1.drop(columns={'FOOD COMMODITY TYPOLOGY', 'FOOD COMMODITY sub-TYPOLOGY'})
df1

,RecipeDB Ingredient,Dietrx_Category,Sueatable Ingredient,Similarity,CF,Count,FOOD COMMODITY GROUP,FOOD COMMODITY TYPOLOGY updated,FOOD COMMODITY ITEM
0,onion,Vegetable,ONION,1.000001,0.24,69096.0,CROPS,VEGETABLE OPENFIELD,ONION
1,yellow onion,Vegetable,ONION,0.816014,0.24,4480.0,CROPS,VEGETABLE OPENFIELD,ONION
2,onion powder,Spice,ONION,0.864563,0.24,3032.0,CROPS,VEGETABLE OPENFIELD,ONION
3,spanish onion,Vegetable,ONION,0.857004,0.24,564.0,CROPS,VEGETABLE OPENFIELD,ONION
4,onion flake,Spice,ONION,0.844400,0.24,556.0,CROPS,VEGETABLE OPENFIELD,ONION
...,...,...,...,...,...,...,...,...,...
7748,palm seed,Nuts and Seeds,PALM NUT,0.907353,0.80,2.0,CROPS,NUT,PALM NUT
7749,beer brown,Beverage,BEER MODULAR CAN,0.845757,0.54,2.0,AGRICULTURAL PROCESSED,BEER,BEER MODULAR CAN
7750,pork shoulder intact,Meat,PORK BONE FREE,0.859510,5.79,2.0,ANIMAL HUSBANDRY,PORK,PORK BONE FREE MEAT
7751,headless prawn,Seafood,PRAWN FROZEN,0.810220,17.73,2.0,FISHING,SHELLFISH FROZEN,PRAWN (F)
7752,rock melon,Fruit,ROCKMELON,0.920289,0.39,2.0,CROPS,FRUIT OPENFIELD,ROCKMELON

In [47]:
sueatf = pd.read_csv("D:\IIITD\Mansi_Thesis_Research\Foodprint\Carbon_Footprint_July23\Data\Sueatable_preprocessed_data.csv")

In [48]:
sueatf = sueatf.drop(columns={'FOOD COMMODITY GROUP','FOOD COMMODITY TYPOLOGY'})
sueatf

,FOOD COMMODITY ITEM,Carbon footprint (kg CO2 eq/kg or litre of food commodity),Type of source,Full Reference,Publication year,System Boundary Distribution,Country,Region,Notes,Reported in other data summaries,Modification of original values
0,BEER GLASS BOTTLE,0.420,EPD,"BIER, 2012. Research on the carbon footprint o...",2012,RETAILER,EUROPE,EUROPE,33.cc.glass bottle,this study,-
1,BEER GLASS BOTTLE,0.568,JOURNAL,"Cimini, A., & Moresi, M. (2016). Carbon footpr...",2016,RETAILER,ITALY,MEDITERRANEAN AREA,66.cc. glass bottle,this study,-
2,BEER GLASS BOTTLE,0.666,JOURNAL,"Cimini, A., & Moresi, M. (2016). Carbon footpr...",2016,RETAILER,ITALY,MEDITERRANEAN AREA,33.cc.glass bottle,this study,-
3,BEER GLASS BOTTLE,0.842,JOURNAL,"Amienyo, D., & Azapagic, A. (2016). Life cycle...",2016,RETAIL,UK,N EUROPE,33.cc.glass bottle,this study,-
4,BEER GLASS BOTTLE,0.961,EPD,Carlsberg. Environmental Product Declaration o...,2018,RETAILER,ITALY,MEDITERRANEAN AREA,33.cc.glass bottle,this study,-
...,...,...,...,...,...,...,...,...,...,...,...
3333,OCTOPUS (F),7.879,JOURNAL,"VÃ zquez-Rowe, I., M.T. Moreira, G. Feijoo. En...",2012,"SB spanish market, imported",CHILE,S AMERICA,wild,BCFN (double pyramid 2016),P
3334,PRAWNS/SHRIMP (F),5.805,LCA DATABASE,"LCA Food, viewed on June 2013. <www.LCAfood.dk>",2010,SB is calculated as the mean value of CF betwe...,DENMARK,N EUROPE,wild,BCFN (double pyramid 2016),P
3335,PRAWNS/SHRIMP (F),7.200,JOURNAL,"Farmery, A., C. Gardner, B. S. Green, S. Jenni...",2015,RDC,AUSTRALIA,OCEANIA,frozen,Clune et al 2017 database,-
3336,PRAWNS/SHRIMP (F),22.930,JOURNAL,"Ziegler, F., J.L. Eichelsheim, A. Emanuelsson,...",2009,"IMPORTED FROM SPAIN, PORT",SENEGAL,AFRICA,wild,BCFN (double pyramid 2016),-
3337,PRAWNS/SHRIMP (F),35.000,JOURNAL,"Ziegler, F., A. Emanuelsson, J. L. Eichelsheim...",2011,RDC,SENEGAL,AFRICA,wild,Clune et al 2017 database,-

In [50]:
def custom_title_case(value):
    exceptions = ["EU", "UK", "USA", "US"]
    words = value.split()
    words = [word if word.upper() in exceptions else word.title() for word in words]
    return ' '.join(words)

# Apply title case with exceptions to the 'Region' column
sueatf['Region'] = sueatf['Region'].apply(custom_title_case)
sueatf['Country'] = sueatf['Country'].apply(custom_title_case)

In [51]:
# sueatf['Region'] = sueatf['Region'].apply(lambda x: x.title())
# sueatf['Country'] = sueatf['Country'].apply(lambda x: x.title())
sueatf['Type of source'] = sueatf['Type of source'].apply(lambda x: x.title())

sueatf

,FOOD COMMODITY ITEM,Carbon footprint (kg CO2 eq/kg or litre of food commodity),Type of source,Full Reference,Publication year,System Boundary Distribution,Country,Region,Notes,Reported in other data summaries,Modification of original values
0,BEER GLASS BOTTLE,0.420,Epd,"BIER, 2012. Research on the carbon footprint o...",2012,RETAILER,Europe,Europe,33.cc.glass bottle,this study,-
1,BEER GLASS BOTTLE,0.568,Journal,"Cimini, A., & Moresi, M. (2016). Carbon footpr...",2016,RETAILER,Italy,Mediterranean Area,66.cc. glass bottle,this study,-
2,BEER GLASS BOTTLE,0.666,Journal,"Cimini, A., & Moresi, M. (2016). Carbon footpr...",2016,RETAILER,Italy,Mediterranean Area,33.cc.glass bottle,this study,-
3,BEER GLASS BOTTLE,0.842,Journal,"Amienyo, D., & Azapagic, A. (2016). Life cycle...",2016,RETAIL,UK,N Europe,33.cc.glass bottle,this study,-
4,BEER GLASS BOTTLE,0.961,Epd,Carlsberg. Environmental Product Declaration o...,2018,RETAILER,Italy,Mediterranean Area,33.cc.glass bottle,this study,-
...,...,...,...,...,...,...,...,...,...,...,...
3333,OCTOPUS (F),7.879,Journal,"VÃ zquez-Rowe, I., M.T. Moreira, G. Feijoo. En...",2012,"SB spanish market, imported",Chile,S America,wild,BCFN (double pyramid 2016),P
3334,PRAWNS/SHRIMP (F),5.805,Lca Database,"LCA Food, viewed on June 2013. <www.LCAfood.dk>",2010,SB is calculated as the mean value of CF betwe...,Denmark,N Europe,wild,BCFN (double pyramid 2016),P
3335,PRAWNS/SHRIMP (F),7.200,Journal,"Farmery, A., C. Gardner, B. S. Green, S. Jenni...",2015,RDC,Australia,Oceania,frozen,Clune et al 2017 database,-
3336,PRAWNS/SHRIMP (F),22.930,Journal,"Ziegler, F., J.L. Eichelsheim, A. Emanuelsson,...",2009,"IMPORTED FROM SPAIN, PORT",Senegal,Africa,wild,BCFN (double pyramid 2016),-
3337,PRAWNS/SHRIMP (F),35.000,Journal,"Ziegler, F., A. Emanuelsson, J. L. Eichelsheim...",2011,RDC,Senegal,Africa,wild,Clune et al 2017 database,-

In [52]:
# Group by 'Sueatable Ingredient' and aggregate other information
grouped = sueatf.groupby('FOOD COMMODITY ITEM').agg({
    'Region': lambda x: x.unique().tolist(),
    'Country': lambda x: x.unique().tolist(),
    'Full Reference': lambda x: x.unique().tolist(),
    'Publication year': lambda x: x.unique().tolist(),
    'Type of source': lambda x: x.unique().tolist()
}).reset_index()

grouped

,FOOD COMMODITY ITEM,Region,Country,Full Reference,Publication year,Type of source
0,ALFONSINO,[Mediterranean Area],[Spain],"[Iribarren, D., I. VÃ¡zquez-Rowe, A. Hospido, ...",[2010],[Journal]
1,ALMOND,"[N America, Mediterranean Area, World]","[USA, Spain, World Estimate, Greece]","[Kendall, A. and S. B. Brodt (2014). Comparing...","[2014, 2015, 2012, 2017]","[Conference, Journal]"
2,ALMOND COVERED WITH CHOCOLATE,[N America],[USA],"[Volpe, R., Messineo, S., Volpe, M., & Messine...",[2015],[Journal]
3,ALMOND MILK,[N America],[USA],"[Feraldi, R., M. Huff, A. M. Molen and H. New ...",[2012],[Conference]
4,ALMOND PASTE,[N America],[USA],"[Volpe, R., Messineo, S., Volpe, M., & Messine...",[2015],[Journal]
...,...,...,...,...,...,...
320,YOGURT LACTOSE FREE,[Mediterranean Area],[Italy],[Granarolo. Dichiarazione ambientale di prodot...,"[2018, 2015]",[Epd]
321,YOGURT WHITE,"[N Europe, N America, Mediterranean Area, Europe]","[Austria, Norway, USA, Sweden, Canada, N Europ...","[Lindenthal, T., T. Markut, S. HÃ¶rtenhuber an...","[2010, 2012, 2013, 2008, 2014, 2009, 2017, 201...","[Conference, Journal, Report, Epd]"
322,ZUCCHINI,"[N Europe, Oceania]","[Sweden, Austria, Switzerland, Australia]","[GonzÃ¡lez, A. D., B. Frostell and A. Carlsson...","[2011, 2010, 2016]","[Journal, Conference, Report]"
323,ZUCCHINI (F),[N Europe],[Switzerland],"[Jungbluth, N., Keller, R., & KÃ¶nig, A. (2016...",[2016],[Journal]
324,ZUCCHINI (g),[Mediterranean Area],[Italy],"[Cellura, M., Ardente, F., Longo, S., (2012). ...",[2012],[Journal]

In [53]:
final = pd.merge(df1,grouped,on='FOOD COMMODITY ITEM', how = 'left')
final = final.drop(columns={'FOOD COMMODITY ITEM'})
final = final.rename(columns={'Dietrx_Category':'Category', 'FOOD COMMODITY GROUP':'Food Commodity Group','FOOD COMMODITY TYPOLOGY updated':'Food Commodity Typology', 'Publication year':'Publication Year', 'CF':'Carbon Footprint', 'Type of source':'Source Type'})
final

,RecipeDB Ingredient,Category,Sueatable Ingredient,Similarity,Carbon Footprint,Count,Food Commodity Group,Food Commodity Typology,Region,Country,Full Reference,Publication Year,Source Type
0,onion,Vegetable,ONION,1.000001,0.24,69096.0,CROPS,VEGETABLE OPENFIELD,"[N Europe, Oceania, Asia]","[Sweden, Denmark, New Zealand, UK, Japan, Aust...","[Cederberg, C., M. Wivstad, P. Bergkvist, B. M...","[2005, 2006, 2011, 2009, 2008, 2010, 2006 (2010)]","[Report, Journal, Conference]"
1,yellow onion,Vegetable,ONION,0.816014,0.24,4480.0,CROPS,VEGETABLE OPENFIELD,"[N Europe, Oceania, Asia]","[Sweden, Denmark, New Zealand, UK, Japan, Aust...","[Cederberg, C., M. Wivstad, P. Bergkvist, B. M...","[2005, 2006, 2011, 2009, 2008, 2010, 2006 (2010)]","[Report, Journal, Conference]"
2,onion powder,Spice,ONION,0.864563,0.24,3032.0,CROPS,VEGETABLE OPENFIELD,"[N Europe, Oceania, Asia]","[Sweden, Denmark, New Zealand, UK, Japan, Aust...","[Cederberg, C., M. Wivstad, P. Bergkvist, B. M...","[2005, 2006, 2011, 2009, 2008, 2010, 2006 (2010)]","[Report, Journal, Conference]"
3,spanish onion,Vegetable,ONION,0.857004,0.24,564.0,CROPS,VEGETABLE OPENFIELD,"[N Europe, Oceania, Asia]","[Sweden, Denmark, New Zealand, UK, Japan, Aust...","[Cederberg, C., M. Wivstad, P. Bergkvist, B. M...","[2005, 2006, 2011, 2009, 2008, 2010, 2006 (2010)]","[Report, Journal, Conference]"
4,onion flake,Spice,ONION,0.844400,0.24,556.0,CROPS,VEGETABLE OPENFIELD,"[N Europe, Oceania, Asia]","[Sweden, Denmark, New Zealand, UK, Japan, Aust...","[Cederberg, C., M. Wivstad, P. Bergkvist, B. M...","[2005, 2006, 2011, 2009, 2008, 2010, 2006 (2010)]","[Report, Journal, Conference]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7748,palm seed,Nuts and Seeds,PALM NUT,0.907353,0.80,2.0,CROPS,NUT,[World],[World Estimate],"[Audsley, E., M. Brander, J. Chatterton, D. Mu...",[2009],[Report]
7749,beer brown,Beverage,BEER MODULAR CAN,0.845757,0.54,2.0,AGRICULTURAL PROCESSED,BEER,[Mediterranean Area],[Italy],[Carlsberg. Environmental Product Declaration ...,[2018],[Epd]
7750,pork shoulder intact,Meat,PORK BONE FREE,0.859510,5.79,2.0,ANIMAL HUSBANDRY,PORK,"[E Europe, N Europe, Oceania, Mediterranean Ar...","[Latvia, Denmark, Lithuania, Slovakia, UK, Swe...","[Lesschen, J. P., M. van den Berg, H. J. Westh...","[2011, 2010, 2004, 2009, 2014, 2005, 2008, 201...","[Journal, Lca Database, Report, Conference]"
7751,headless prawn,Seafood,PRAWN FROZEN,0.810220,17.73,2.0,FISHING,SHELLFISH FROZEN,NaN,NaN,NaN,NaN,NaN
7752,rock melon,Fruit,ROCKMELON,0.920289,0.39,2.0,CROPS,FRUIT OPENFIELD,[Oceania],[Australia],"[Maraseni, T. N., G. Cockfield, J. Maroulis an...",[2010],[Journal]

In [54]:
# Reorder columns
column_order = ['RecipeDB Ingredient', 'Category', 'Sueatable Ingredient', 'Food Commodity Group',
    'Food Commodity Typology', 'Region', 'Country', 'Carbon Footprint', 'Full Reference', 'Publication Year', 'Source Type']

final = final[column_order]

final

,RecipeDB Ingredient,Category,Sueatable Ingredient,Food Commodity Group,Food Commodity Typology,Region,Country,Carbon Footprint,Full Reference,Publication Year,Source Type
0,onion,Vegetable,ONION,CROPS,VEGETABLE OPENFIELD,"[N Europe, Oceania, Asia]","[Sweden, Denmark, New Zealand, UK, Japan, Aust...",0.24,"[Cederberg, C., M. Wivstad, P. Bergkvist, B. M...","[2005, 2006, 2011, 2009, 2008, 2010, 2006 (2010)]","[Report, Journal, Conference]"
1,yellow onion,Vegetable,ONION,CROPS,VEGETABLE OPENFIELD,"[N Europe, Oceania, Asia]","[Sweden, Denmark, New Zealand, UK, Japan, Aust...",0.24,"[Cederberg, C., M. Wivstad, P. Bergkvist, B. M...","[2005, 2006, 2011, 2009, 2008, 2010, 2006 (2010)]","[Report, Journal, Conference]"
2,onion powder,Spice,ONION,CROPS,VEGETABLE OPENFIELD,"[N Europe, Oceania, Asia]","[Sweden, Denmark, New Zealand, UK, Japan, Aust...",0.24,"[Cederberg, C., M. Wivstad, P. Bergkvist, B. M...","[2005, 2006, 2011, 2009, 2008, 2010, 2006 (2010)]","[Report, Journal, Conference]"
3,spanish onion,Vegetable,ONION,CROPS,VEGETABLE OPENFIELD,"[N Europe, Oceania, Asia]","[Sweden, Denmark, New Zealand, UK, Japan, Aust...",0.24,"[Cederberg, C., M. Wivstad, P. Bergkvist, B. M...","[2005, 2006, 2011, 2009, 2008, 2010, 2006 (2010)]","[Report, Journal, Conference]"
4,onion flake,Spice,ONION,CROPS,VEGETABLE OPENFIELD,"[N Europe, Oceania, Asia]","[Sweden, Denmark, New Zealand, UK, Japan, Aust...",0.24,"[Cederberg, C., M. Wivstad, P. Bergkvist, B. M...","[2005, 2006, 2011, 2009, 2008, 2010, 2006 (2010)]","[Report, Journal, Conference]"
...,...,...,...,...,...,...,...,...,...,...,...
7748,palm seed,Nuts and Seeds,PALM NUT,CROPS,NUT,[World],[World Estimate],0.80,"[Audsley, E., M. Brander, J. Chatterton, D. Mu...",[2009],[Report]
7749,beer brown,Beverage,BEER MODULAR CAN,AGRICULTURAL PROCESSED,BEER,[Mediterranean Area],[Italy],0.54,[Carlsberg. Environmental Product Declaration ...,[2018],[Epd]
7750,pork shoulder intact,Meat,PORK BONE FREE,ANIMAL HUSBANDRY,PORK,"[E Europe, N Europe, Oceania, Mediterranean Ar...","[Latvia, Denmark, Lithuania, Slovakia, UK, Swe...",5.79,"[Lesschen, J. P., M. van den Berg, H. J. Westh...","[2011, 2010, 2004, 2009, 2014, 2005, 2008, 201...","[Journal, Lca Database, Report, Conference]"
7751,headless prawn,Seafood,PRAWN FROZEN,FISHING,SHELLFISH FROZEN,NaN,NaN,17.73,NaN,NaN,NaN
7752,rock melon,Fruit,ROCKMELON,CROPS,FRUIT OPENFIELD,[Oceania],[Australia],0.39,"[Maraseni, T. N., G. Cockfield, J. Maroulis an...",[2010],[Journal]

In [55]:
#title case 

final['RecipeDB Ingredient'] = final['RecipeDB Ingredient'].apply(lambda x: x.title())
final['Sueatable Ingredient'] = final['Sueatable Ingredient'].apply(lambda x: x.title())
final['Food Commodity Group'] = final['Food Commodity Group'].apply(lambda x: x.title())
final['Food Commodity Typology'] = final['Food Commodity Typology'].apply(lambda x: x.title())
# final['Region'] = final['Region'].apply(lambda x: [item.title() for item in x])
# final['Country'] = final['Country'].apply(lambda x: [item.title() for item in x])
# final['Source Type'] = final['Source Type'].apply(lambda x: [item.title() for item in x])

final

C:\Users\Mansi Goel\AppData\Local\Temp\ipykernel_28316\3261323068.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final['RecipeDB Ingredient'] = final['RecipeDB Ingredient'].apply(lambda x: x.title())
C:\Users\Mansi Goel\AppData\Local\Temp\ipykernel_28316\3261323068.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final['Sueatable Ingredient'] = final['Sueatable Ingredient'].apply(lambda x: x.title())
C:\Users\Mansi Goel\AppData\Local\Temp\ipykernel_28316\3261323068.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final['Food Commodity Group'] = final['Food Commodity Group'].apply(lambda x: x.title())
C:\Users\Mansi Goel\AppData\Local\Temp\ipykernel_28316\3261323068.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final['Food Commodity Typology'] = final['Food Commodity Typology'].apply(lambda x: x.title())

,RecipeDB Ingredient,Category,Sueatable Ingredient,Food Commodity Group,Food Commodity Typology,Region,Country,Carbon Footprint,Full Reference,Publication Year,Source Type
0,Onion,Vegetable,Onion,Crops,Vegetable Openfield,"[N Europe, Oceania, Asia]","[Sweden, Denmark, New Zealand, UK, Japan, Aust...",0.24,"[Cederberg, C., M. Wivstad, P. Bergkvist, B. M...","[2005, 2006, 2011, 2009, 2008, 2010, 2006 (2010)]","[Report, Journal, Conference]"
1,Yellow Onion,Vegetable,Onion,Crops,Vegetable Openfield,"[N Europe, Oceania, Asia]","[Sweden, Denmark, New Zealand, UK, Japan, Aust...",0.24,"[Cederberg, C., M. Wivstad, P. Bergkvist, B. M...","[2005, 2006, 2011, 2009, 2008, 2010, 2006 (2010)]","[Report, Journal, Conference]"
2,Onion Powder,Spice,Onion,Crops,Vegetable Openfield,"[N Europe, Oceania, Asia]","[Sweden, Denmark, New Zealand, UK, Japan, Aust...",0.24,"[Cederberg, C., M. Wivstad, P. Bergkvist, B. M...","[2005, 2006, 2011, 2009, 2008, 2010, 2006 (2010)]","[Report, Journal, Conference]"
3,Spanish Onion,Vegetable,Onion,Crops,Vegetable Openfield,"[N Europe, Oceania, Asia]","[Sweden, Denmark, New Zealand, UK, Japan, Aust...",0.24,"[Cederberg, C., M. Wivstad, P. Bergkvist, B. M...","[2005, 2006, 2011, 2009, 2008, 2010, 2006 (2010)]","[Report, Journal, Conference]"
4,Onion Flake,Spice,Onion,Crops,Vegetable Openfield,"[N Europe, Oceania, Asia]","[Sweden, Denmark, New Zealand, UK, Japan, Aust...",0.24,"[Cederberg, C., M. Wivstad, P. Bergkvist, B. M...","[2005, 2006, 2011, 2009, 2008, 2010, 2006 (2010)]","[Report, Journal, Conference]"
...,...,...,...,...,...,...,...,...,...,...,...
7748,Palm Seed,Nuts and Seeds,Palm Nut,Crops,Nut,[World],[World Estimate],0.80,"[Audsley, E., M. Brander, J. Chatterton, D. Mu...",[2009],[Report]
7749,Beer Brown,Beverage,Beer Modular Can,Agricultural Processed,Beer,[Mediterranean Area],[Italy],0.54,[Carlsberg. Environmental Product Declaration ...,[2018],[Epd]
7750,Pork Shoulder Intact,Meat,Pork Bone Free,Animal Husbandry,Pork,"[E Europe, N Europe, Oceania, Mediterranean Ar...","[Latvia, Denmark, Lithuania, Slovakia, UK, Swe...",5.79,"[Lesschen, J. P., M. van den Berg, H. J. Westh...","[2011, 2010, 2004, 2009, 2014, 2005, 2008, 201...","[Journal, Lca Database, Report, Conference]"
7751,Headless Prawn,Seafood,Prawn Frozen,Fishing,Shellfish Frozen,NaN,NaN,17.73,NaN,NaN,NaN
7752,Rock Melon,Fruit,Rockmelon,Crops,Fruit Openfield,[Oceania],[Australia],0.39,"[Maraseni, T. N., G. Cockfield, J. Maroulis an...",[2010],[Journal]

In [56]:
final.to_csv("D:\IIITD\Mansi_Thesis_Research\Foodprint\Carbon_Footprint_July23\Data\Ingredient_details_server.csv", index=False)